package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Template
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'ProjectToBreak1_SubprojectToBreakTemplate2344'
in the project with id = 'ProjectToBreak1', and delete the patch script.
*/
create(RelativeId("ProjectToBreak1"), Template({
    id("ProjectToBreak1_SubprojectToBreakTemplate2344")
    name = "template1"

    steps {
        script {
            id = "RUNNER_14"
            scriptContent = "echo template"
        }
    }
}))

